Repository yiisoft/var-dumper, pull requests merged in 2021-02, with the labels that each got.

#44 Fix export
  src/ClosureExporter.php
  src/TokenHelper.php
  src/UseStatementParser.php
Labels: type:test

#45 Cleanup, add d() and dd() functions, add test cases
  .scrutinizer.yml
  README.md
  composer.json
  src/ClosureExporter.php
  src/TokenHelper.php
  src/UseStatementParser.php
  src/VarDumper.php
  src/functions.php
  tests/TestAsset/DummyArrayableWithClosure.php
  tests/TestAsset/DummyDebugInfo.php
  tests/TestAsset/DummyIteratorAggregateWithClosure.php
  tests/TestAsset/DummyStringableWithClosure.php
  tests/UseStatementParserTest.php
  tests/VarDumperTest.php
Labels: status:code review

#46 Fix dump functions and readme, improve VarDumper::export()
  CHANGELOG.md
  README.md
  infection.json.dist
  src/VarDumper.php
  src/functions.php
  tests/TestAsset/DummyJsonSerializableWithClosure.php
  tests/VarDumperTest.php
Labels: status:code review

#48 Remove unused $objects property from VarDumper
  CHANGELOG.md
  src/VarDumper.php
Labels: status:ready for merge

#49 Issue exporting closures with use under PHP 8
  CHANGELOG.md
  src/ClosureExporter.php
  tests/ClosureExporterTest.php
Labels: status:code review

#50 Fix exporting closures with use long namespace under PHP 7.4
  CHANGELOG.md
  src/ClosureExporter.php
  tests/ClosureExporterTest.php
Labels: status:code review
